<?php

use Phalcon\Encryption\Crypt;
use Phalcon\Di\Di;
use Phalcon\Config\Config;


echo "<h1>Hello</h1>";

$config = Di::getDefault()->getShared('config');
//echo $config->path('application.migrationsDir');
$key = $config->path('application.cryptSalt');
//echo '<h2>key='.$key,'</h2>';

$crypt = new Crypt();
$crypt->setKey($key);

$encrypted_password = 'IAmSpongeBobsPassword';
$encrypted = $crypt->encrypt($encrypted_password);
